Settings:
  Spawn:
    yaw: 90
    x: 0.0
    y: 0.0
    z: 0.0
    world: world
  Sprawdzarka:
    yaw: 90
    x: 0.0
    y: 0.0
    z: 0.0
    world: world

  Command:
    logout: "tempipban {player} 48h Wylogowano podczas sprawdzania"
    ban: "tempban {player} 7d Posiadanie cheatow"
    przyznanie: "tempban {player} 3d Przyznanie do cheatow"

  Allowed_Commands:
    - "tpa"